export const env_vars = {
  THIRD_WEB_CLIENT_ID:
    process.env.THIRD_WEB_CLIENT_ID || process.env.NEXT_PUBLIC_THIRD_WEB_CLIENT_ID!,
  THIRD_WEB_SECRET_KEY:
    process.env.THIRD_WEB_SECRET_KEY || process.env.NEXT_PUBLIC_THIRD_WEB_SECRET_KEY!,
  ROUTER_ADDRESS: process.env.ROUTER_ADDRESS || process.env.NEXT_PUBLIC_ROUTER_ADDRESS!,
  RPC_URL: process.env.RPC_URL || process.env.NEXT_PUBLIC_RPC_URL!,
  SWAP_ROUTER_ADDRESS:
    process.env.SWAP_ROUTER_ADDRESS || process.env.NEXT_PUBLIC_SWAP_ROUTER_ADDRESS!,
  SWAP_BATCHER_ADDRESS:
    process.env.SWAP_BATCHER_ADDRESS || process.env.NEXT_PUBLIC_SWAP_BATCHER_ADDRESS!,
}
